"""add phone column in user table

Revision ID: 744577f506ed
Revises: a2adad1d9f7e
Create Date: 2026-03-22 02:03:37.178906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '744577f506ed'
down_revision: Union[str, Sequence[str], None] = 'a2adad1d9f7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Phone', sa.String(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'Phone')
    # ### end Alembic commands ###
